#!/bin/bash
ml anaconda/3
ml julia

lam_lst=( 1 5 10 50 100 300 700 1000 )
for j in "${lam_lst[@]}"
do
	mkdir lam_$j
		

	cp * lam_$j/
	
	cd lam_$j/
	
	sed -i "s/^lam = .*/lam = ${j}/" hoppingVMaker.py
	
	python3 hoppingVMaker.py
	julia compressMPO.jl Vuncomp
	
	sbatch jobscript
	
	cd ../
	
done
