#!/bin/bash
ml anaconda/3
ml julia

lam_lst=( 1 50 100 200 400 700 )
for j in "${lam_lst[@]}"
do
	mkdir lam_$j
		

	cp * lam_$j/
	
	cd lam_$j/
	
	sed -i "s/^lam = .*/lam = ${j}/" hoppingVMaker.py
	
	python3 hoppingVMaker.py
	julia compressMPO.jl Vuncomp
	
	sbatch jobscript
	
	cd ../
	
done
